# SPDX-License-Identifier: GPL-2.0-or-later

KEY_SIZE_RATIO = 3.2
KEY_SPACING_RATIO = 0.2
KEY_ROUNDNESS = 0.08

KEYCODE_BTN_RATIO = 3

WINDOW_WIDTH, WINDOW_HEIGHT = 1024, 768

KEYBOARD_WIDGET_PADDING = 5
# the keyboard drawing shrinks so it takes at most this share of the window
KEYBOARD_WIDGET_FIT_WIDTH = 0.9
KEYBOARD_WIDGET_FIT_HEIGHT = 0.85

KEYBOARD_WIDGET_MASK_HEIGHT = 0.65
KEYBOARD_WIDGET_NONMASK_PADDING = 0.02

SHADOW_SIDE_PADDING = 0.1
SHADOW_TOP_PADDING = 0.05
SHADOW_BOTTOM_PADDING = 0.15
